security:
    password_hashers:
        App\Entity\User:
            algorithm: bcrypt

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        main:
            pattern: ^/
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: homepage
            logout:
                path: app_logout
                target: homepage
            remember_me: true

    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]
        ROLE_USER: [ROLE_BANNED]

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/user, roles: ROLE_USER }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
