security:
    password_hashers:
        App\Entity\User:
            algorithm: bcrypt
            cost: 12

    firewalls:
        main:
            form_login:
                login_path: login
                check_path: login
                default_target_path: /home
            logout:
                path: logout
                target: /login
            # Add the user provider here
            user_provider: app_user_provider

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/home, roles: ROLE_USER }

    # Define the user provider
    services:
        app_user_provider:
            class: App\Security\UserProvider
